blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/discussions
    about: Please discuss things here.
