name: Suggest a feature!
description: Have an idea for a WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsiteWhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite language feature? Suggest it here!
body:
  - type: textarea
    id: about
    attributes:
      label: What is your idea?
      description: Clearly state what you'd like to see added to WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite.
      placeholder: I'd love to see an alias for `+` called `plus` added to the WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsiteLCtrlRAlt language.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Give an example.
      description: Give an example in the WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite language on how this feature would look. Ideally, you'd also provide a comparison to how it has to be done currently.
      placeholder: |
        // Currently, WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite requires people to do this:
        print(2 + 3)!
        // With this proposed change, you'd be able to do this:
        print(2 plus 3)
      render: Java
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why should WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite adopt this?
      description: Give a clear but not overly long description on why this feature would be worth adopting to WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite.
      placeholder: This should be done because of code readability. The `+` operator may not be known to everyone reading the code, and discriminating against certain people is a bad practice.
    validations:
      required: true
labels:
  - enhancement
